[settings]
experimental = true
lockfile = true

[tools]
# core
go = "latest"
python = "latest"
rust = "latest"
node = "latest"
# aqua + ubi
"aqua:jqlang/jq" = "1.8.1"
"aqua:a8m/envsubst" = "1.4.3"
"aqua:go-task/task" = "3.49.1"
"aqua:cli/cli" = "2.89.0" # gh
"aqua:junegunn/fzf" = "0.70.0"
"aqua:bitwarden/clients" = "2026.2.0"
"ubi:ajeetdsouza/zoxide" = "0.9.9"
"ubi:starship/starship" = "1.24.2"
"ubi:sharkdp/bat" = "0.26.1"
"ubi:yt-dlp/yt-dlp" = "2026.03.17"
"ubi:pranshuparmar/witr" = "0.3.1"
# go
"go:github.com/kubecolor/kubecolor" = "0.5.3"
"go:github.com/ankitpokhrel/jira-cli/cmd/jira" = "1.7.0"
# pipx
"pipx:icdiff" = "2.0.7"
"aqua:dandavison/delta" = "0.16.5"
